### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by aschmu** [rosette-api/rosette-elasticsearch-plugin#20]
Hello, 

I was looking for a docker image in order to test out the rosette plugin but I can't find the docker file !

**Comment by seth-basistech** [comment]
Hi @aschmu 
Apologies for the confusing README.  The Docker image the README is referring to is generally used for developers testing changes to the plugin itself.

You can [sign up](https://developer.rosette.com/) for a trial account to test the Elasticsearch plugin against our hosted service.  At this time, a business email is required to sign-up.  We also offer an on-premise version.  If you'd like more information about either, please send an email to support@rosette.com
