### ISSUE TITLE
Can this support multi language search?

### ISSUE THREAD

**Issue by wavelet123** [rosette-api/rosette-elasticsearch-plugin#22]
Hi,
We need to do nick name search in 35,000,000 records,but there are Arabic,English,Spanish etc in this field.
Could you please advise?

Thanks

**Comment by seth-basistech** [comment]
@wavelet123 please take a look at our [name-similarity functionality](https://developer.rosette.com/features-and-functions#name-similarity) as a starting point.  If you need more information, feel free to [email us](mailto:support@rosette.com).
